// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://cpgwnqiywsawepdkccpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwZ3ducWl5d3Nhd2VwZGtjY3BqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1NTU2MzgsImV4cCI6MjA3ODEzMTYzOH0.ONAuHNg9H4WMSudDaEoTyfXhnU2vkWXsSpadlNeAXzE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});